@startuml FactoryMethod
skinparam backgroundColor #1e1e1e
skinparam classBackgroundColor #2d2d2d
skinparam classBorderColor #999999
skinparam classArrowColor #cccccc
skinparam shadowing false
skinparam roundcorner 10
hide empty members

interface Product {
  +operation(): str
}

class ConcreteProductA {
  +operation(): str
}
class ConcreteProductB {
  +operation(): str
}

abstract class Creator {
  +factory_method(): Product
  +some_operation(): str
}
class ConcreteCreatorA {
  +factory_method(): Product
}
class ConcreteCreatorB {
  +factory_method(): Product
}

Product <|.. ConcreteProductA
Product <|.. ConcreteProductB
Creator <|-- ConcreteCreatorA
Creator <|-- ConcreteCreatorB
Creator ..> Product : crea

@enduml